# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002bd49725ea47b990334bb59049de64395659b89adf70993ea535c5da168b678ac3c78ecfaa004524ec8e089937a2b1333907872bd7be30f747ff745d3f7bff

test:
  secret_key_base: 314cfeed5a8cbf17e9ac891d1821a4808a6ec60977cdbf5e5ce804187b615067fdf97eaf3cffb291c961f0e0ce37dfec281573fff63897672cc7be7d9aab8aed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
